image: maven:3.8.2-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  NEXUS_REPO_RELEASE_URL: $Nexus_REPO_REALEASE_URL
  NEXUS_REPO_DOCKER_URL: $Nexus_REPO_DOCKER_PRIVATE_URL
  NEXUS_USER: $Nexus_REPO_USER
  NEXUS_PASSWORD: $Nexus_REPO_PASS
  NEXUS_REPO_GROUP_URL: $Nexus_REPO_GROUP_URL

cache:
  paths:
    - ./.m2/repository
  key: "$CI_BUILD_REF_NAME"

stages:
  - build
  - test
  - package
  - nexus
  - dev_deploy
  - homol_deploy

codebuild:
  tags: 
    - build
  stage: build 
  script:   
    - mvn $MAVEN_CLI_OPTS compile -Dmaven.test.skip=true 

codetest: 
  tags: 
    - build 
  stage: test 
  script: 
    - mvn $MAVEN_CLI_OPTS test 
    - echo "Código testado" 

Codepackage: 
  tags: 
    - build 
  stage: package 
  script: 
    - mvn $MAVEN_CLI_OPTS package -Dmaven.test.skip=true 
    - echo "Pacote criado." 
  artifacts: 
    paths: 
        - target/*.jar 
  only: 
    - master 

Codedeploynexus: 
  tags: 
    - build 
  stage: nexus 
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true 
    - echo "instalando o pacote no repositorio" 
    - echo "deploy docker image"  
  only: 
    - master

DeployDev:
  stage: dev_deploy
  tags: 
    - build
  dependencies:
    - codebuild
  script:
#    - VERSION=$(mvn --non-recursive help:evaluate -Dexpression=project.version | grep -v '\[.*'| tail -1)
    - export VERSION=0.0.1
    - echo $VERSION
    - "export payload_file='{\"env\":[{\"name\":\"VERSION\",\"value\":\"'\"$VERSION\"'\"},{\"name\":\"Nexus_REPO_USER\",\"value\":\"'\"$NEXUS_USER\"'\"},{\"name\":\"Nexus_REPO_PASS\",\"value\":\"'\"$NEXUS_PASSWORD\"'\"},{\"name\":\"Nexus_REPO_GROUP_URL\",\"value\":\"'\"$NEXUS_REPO_GROUP_URL\"'\"}]}'"
    - "echo $payload_file >> payload_file.json"
    - "cat payload_file.json"
    - "curl -H Content-Type:application/json --data-binary @payload_file.json -X POST -k https://api.ose43prd.copel.nt:6443/apis/build.openshift.io/v1/namespaces/smanager-greeting-rest-dsv/buildconfigs/smanager-greeting-rest-dsv-bc/webhooks/6f2c1de6e604aeeb/generic"
  only: 
    - dev

DeployHomol:
  stage: homol_deploy
  tags: 
    - build
  dependencies:
    - codebuild
  script:
    - VERSION=$(mvn --non-recursive help:evaluate -Dexpression=project.version | grep -v '\[.*'| tail -1)
    - echo $VERSION
    - "export payload_file='{\"env\":[{\"name\":\"VERSION\",\"value\":\"'\"$VERSION\"'\"},{\"name\":\"Nexus_REPO_USER\",\"value\":\"'\"$NEXUS_USER\"'\"},{\"name\":\"Nexus_REPO_PASS\",\"value\":\"'\"$NEXUS_PASSWORD\"'\"},{\"name\":\"Nexus_REPO_GROUP_URL\",\"value\":\"'\"$NEXUS_REPO_GROUP_URL\"'\"}]}'"
    - "echo $payload_file >> payload_file.json"
    - "cat payload_file.json"
    - "curl -H Content-Type:application/json --data-binary @payload_file.json -X POST -k https://api.cluster-41d5.sandbox1110.opentlc.com:6443/apis/build.openshift.io/v1/namespaces/copel-greeting-rest-homol/buildconfigs/copel-greeting-rest-homol/webhooks/12c9c026ffa40d31/generic"
  only: 
    - homol
